### ISSUE TITLE
Related Repositories Give 404

### ISSUE THREAD

**Issue by paked** [Razish/xsngine#20]
[The two links in the README of "related" repositories are broken.](https://github.com/Razish/xsngine#related-repos)

**Comment by Razish** [comment]
xsngine-assets correctly directs me to https://github.com/Razish/xsngine-assets, xsngine-tools simply doesn't exist yet.
If that's what you're experiencing, then everything is working as intended.

**Comment by paked** [comment]
Brilliant ;)

**Comment by Razish** [comment]
xsngine-tools now exists and will soon contain some .XMF utility scripts.
